# @name readOrderById
GET https://services.odata.org/V2/Northwind/Northwind.svc/Orders(10248)
    ?$format=json
    &$expand=Customer,Order_Details
Content-Type: application/json
Accept: */*
###

# @name plantJSON
POST http://localhost:4004/plantJSON?mode=v2
Content-Type: application/json

{{readOrderById.response.body.$}}
###