# @name readOrderById
GET https://services.odata.org/V2/Northwind/Northwind.svc/Orders(10248)
    ?$format=json
    &$expand=Customer,Order_Details
Content-Type: application/json
Accept: */*
###

@responseObject = {{readOrderById.response.body.$}}

# @name plantUml
# currently not working, because REST client needs to support jsonStringify to be able to passthrough 
POST http://localhost:4004/plantuml/renderV2
Content-Type: application/json

{
    "json": "{{$jsonStringify %responseObject}}"
}
###